// Copyright 2026 Google LLC

// Note this Gradle build script can only build the sample app and test code. It
// does not build the library itself, which is built using Bazel (see BUILD
// files).

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:9.1.1"
    }
}

allprojects {
  repositories {
    google()
    mavenCentral()
  }
}
