apply plugin: 'com.android.application'

android {
  namespace 'com.google.net.cronet.testing.testapp'
  testNamespace 'com.google.net.cronet.okhttptransport'
  compileSdk 37

  defaultConfig {
    minSdk 24
    targetSdk 37
  }

  sourceSets {
    main {
      java.srcDirs = ['../../java/com/google/net/cronet/testing/testapp']
      manifest.srcFile '../../java/com/google/net/cronet/testing/testapp/AndroidManifest.xml'
      res.srcDirs = ['../../java/com/google/net/cronet/testing/testapp/res']
    }

    androidTest {
      java.srcDirs = ['../../javatests']
      manifest.srcFile '../../javatests/com/google/net/cronet/okhttptransport/InstrumentationTestManifest.xml'
      res.srcDirs = ['../../java/com/google/net/cronet/testing/testapp/res']
    }
  }

  buildTypes {
    proguard {
      proguardFiles 'main.pro'
    }
  }
}

dependencies {
  implementation 'com.google.android.gms:play-services-cronet:18.1.1'
  // Make sure to pull a higher version of Cronet than play-services-cronet
  // depends on, to work around "Namespace 'org.chromium.net' is used in
  // multiple modules" errors in AGP 9. See https://crbug.com/406926302.
  implementation 'org.chromium.net:cronet-api:143.7445.0'
  androidTestImplementation 'com.google.net.cronet:cronet-okhttp:0.1.1'
  androidTestImplementation 'com.google.truth:truth:1.1.3'
  androidTestImplementation 'androidx.test:core:1.7.0'
  androidTestImplementation 'androidx.test:runner:1.7.0'
  androidTestImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
  androidTestImplementation 'androidx.test:runner:1.7.0'
  androidTestImplementation 'androidx.test.ext:junit:1.3.0'
  androidTestImplementation 'com.squareup.okhttp3:okhttp-tls:4.12.0'
}
